name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            pedronl/convert-temp:${{ github.run_number }}
            pedronl/convert-temp:latest
            
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.0
        with:
          image: pedronl/convert-temp:${{ github.run_number }}
          manifests: |
            ./deployment.yaml
          

